trigger: none
 
pr: none
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Calling Kaiburr API..."
        curl -X POST https://kc.kaiburr.com/api/v2/job/TestCaseGeneration/start \
          -H "Authorization: Token $(KAIBURR_TOKEN)" \
          -H "Content-Type: application/json" \
          -d '[{"name": "issues", "value": "[]"}]'